# -*- coding: utf-8 -*-
"""DCUA_Metal_Defects_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cN2X_Fpu--z10tCQ1zXENCiK4z8pqrbe
"""

!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install opencv-python scikit-learn matplotlib seaborn tqdm pandas numpy
!pip install pytorchvideo kagglehub albumentations
!apt-get install ffmpeg

import torch
print(f"PyTorch версия: {torch.__version__}")
print(f"CUDA доступен: {torch.cuda.is_available()}")
print(f"GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Установка CLI
!pip install kaggle

# Загрузите ваш kaggle.json (из аккаунта Kaggle → Account → API → "Create New Token")
from google.colab import files
files.upload()  # Выберите файл kaggle.json

# Настройка
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Скачивание датасета
!kaggle datasets download -d toqaalaaawad/metal-surfaces-defects

# Распаковка
!unzip -q metal-surfaces-defects.zip

!pip install onnx onnxscript torch torchvision torchaudio
import torch
import onnx
import onnxscript

print(f"PyTorch version: {torch.__version__}")
print(f"ONNX version: {onnx.__version__}")
print(f"ONNXScript version: {onnxscript.__version__}")
print("Все пакеты установлены успешно!")

import sys
import os
import random
import time
import json
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Subset
from torchvision import models, transforms
from torchvision.datasets import ImageFolder
from tqdm import tqdm
from sklearn.metrics import normalized_mutual_info_score, adjusted_rand_score
from sklearn.model_selection import train_test_split
from collections import Counter

def set_seed(seed=42):
    """Фиксирует все random seed для воспроизводимости"""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    print(f"✓ Seed фиксирован: {seed}")

set_seed(42)

print("\nЗагрузка и обработка данных...")

import shutil

root_dir = "Metal-surfaces-defects"
base_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

classes = os.listdir(root_dir)
print("Classes found:", classes)

if 'lable' in classes:
    class_path = os.path.join(root_dir, 'lable')
    files = os.listdir(class_path)
    valid_files = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif', '.tiff', '.webp'))]
    if len(valid_files) == 0:
        shutil.rmtree(class_path)
        print("Removed invalid 'lable' folder")
    else:
        print("'lable' has files; check manually:", valid_files)

full_dataset = ImageFolder(root="Metal-surfaces-defects", transform=base_transform)
class_names = full_dataset.classes
print(f"Названия классов: {class_names}")
print(f"Загружено {len(full_dataset)} изображений в {len(full_dataset.classes)} классах.")

indices = np.arange(len(full_dataset))
train_idx, temp_idx = train_test_split(
    indices, test_size=0.2, random_state=42, stratify=full_dataset.targets
)
val_idx, test_idx = train_test_split(
    temp_idx, test_size=0.5, random_state=42,
    stratify=[full_dataset.targets[i] for i in temp_idx]
)

train_dataset = Subset(full_dataset, train_idx)
val_dataset = Subset(full_dataset, val_idx)
test_dataset = Subset(full_dataset, test_idx)
print(f"Train: {len(train_dataset)} | Val: {len(val_dataset)} | Test: {len(test_dataset)}")

import albumentations as A
from albumentations.pytorch import ToTensorV2
import cv2

train_transform = A.Compose([
    A.Resize(224, 224),
    A.RandomRotate90(p=0.5),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.3),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),
    A.GaussNoise(var_limit=(10, 30), p=0.3),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])

val_test_transform = A.Compose([
    A.Resize(224, 224),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])

class AlbumentationsDataset(torch.utils.data.Dataset):
    def __init__(self, subset, transform=None):
        self.subset = subset
        self.transform = transform

    def __len__(self):
        return len(self.subset)

    def __getitem__(self, idx):
        img, label = self.subset[idx]          # img — PIL Image
        img = np.array(img)                    # Albumentations работает с numpy
        if self.transform:
            augmented = self.transform(image=img)
            img = augmented['image']
        return img, label

train_img_dataset = AlbumentationsDataset(train_dataset, transform=train_transform)
val_img_dataset   = AlbumentationsDataset(val_dataset, transform=val_test_transform)
test_img_dataset  = AlbumentationsDataset(test_dataset, transform=val_test_transform)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Устройство: {device}")

resnet = models.resnet18(weights='IMAGENET1K_V1')
resnet.fc = nn.Identity()
resnet = resnet.to(device).eval()

dataloader_full = DataLoader(full_dataset, batch_size=32, shuffle=False, num_workers=2)

embeddings = []
labels = []

with torch.no_grad():
    for images, targets in tqdm(dataloader_full, desc="Извлечение эмбеддингов"):
        images = images.to(device)
        emb = resnet(images)
        embeddings.append(emb.cpu().numpy())
        labels.append(targets.numpy())

embeddings = np.vstack(embeddings)  # (N, 512)
labels = np.hstack(labels)          # (N,)
print(f"Эмбеддинги: {embeddings.shape}, Метки: {labels.shape}")

X_train, X_val, y_train, y_val = train_test_split(
    embeddings[train_idx], labels[train_idx], test_size=0.2, random_state=42, stratify=labels[train_idx]
)

# Тензоры для обучения модели
train_tensor = torch.tensor(X_train, dtype=torch.float32)
val_tensor = torch.tensor(X_val, dtype=torch.float32)

train_loader = DataLoader(train_tensor, batch_size=64, shuffle=True)
val_loader = DataLoader(val_tensor, batch_size=64, shuffle=False)

# Сохраняем истинные метки для оценки в процессе обучения
val_labels = y_val

print(f"Тренировочные эмбеддинги: {X_train.shape}, Валидационные эмбеддинги: {X_val.shape}")

class WorkingVaDE_Metal(nn.Module):
    def __init__(self, input_dim=512, z_dim=32, n_clusters=12):
        super().__init__()
        self.z_dim = z_dim
        self.n_clusters = n_clusters

        # Энкодер
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 500),
            nn.BatchNorm1d(500),
            nn.ReLU(),
            nn.Linear(500, 500),
            nn.BatchNorm1d(500),
            nn.ReLU(),
        )
        self.fc_mu = nn.Linear(500, z_dim)
        self.fc_logvar = nn.Linear(500, z_dim)
        self.fc_gamma = nn.Linear(500, n_clusters)

        # Декодер (восстанавливает эмбеддинги)
        self.decoder = nn.Sequential(
            nn.Linear(z_dim, 500),
            nn.BatchNorm1d(500),
            nn.ReLU(),
            nn.Linear(500, input_dim)
        )

        # GMM prior
        self.gmm_mu = nn.Parameter(torch.randn(n_clusters, z_dim) * 3.0)
        self.gmm_logvar = nn.Parameter(torch.ones(n_clusters, z_dim) * np.log(0.3))
        self.gmm_pi = nn.Parameter(torch.ones(n_clusters) / n_clusters)

    def encode(self, x, temperature=0.3):
        h = self.encoder(x)
        mu = self.fc_mu(h)
        logvar = torch.clamp(self.fc_logvar(h), min=-4, max=3)
        gamma_logits = self.fc_gamma(h)
        gamma = F.softmax(gamma_logits / temperature, dim=-1)
        return mu, logvar, gamma

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        return self.decoder(z)

    def forward(self, x, temperature=0.3):
        mu, logvar, gamma = self.encode(x, temperature)
        z = self.reparameterize(mu, logvar)
        x_recon = self.decode(z)
        return x_recon, z, gamma, mu, logvar

    def compute_gmm_prob(self, z):
        B, D = z.shape
        K = self.n_clusters
        z_exp = z.unsqueeze(1)
        mu_exp = self.gmm_mu.unsqueeze(0)
        logvar_exp = self.gmm_logvar.unsqueeze(0)
        log_prob = -0.5 * (
            D * np.log(2 * np.pi) +
            logvar_exp.sum(-1) +
            ((z_exp - mu_exp) ** 2 / torch.exp(logvar_exp)).sum(-1)
        )
        log_prob = torch.log(self.gmm_pi + 1e-10) + log_prob
        return torch.logsumexp(log_prob, dim=1)

    def update_gmm(self, z, gamma):
        """
        Обновление параметров GMM на основе текущих присваиваний
        Вызывать после каждой эпохи
        """
        with torch.no_grad():
            # gamma: [batch_size, n_clusters]
            # z: [batch_size, z_dim]

            # Сумма вероятностей по каждому кластеру
            N = gamma.sum(0) + 1e-10  # [n_clusters]

            # Обновляем веса
            self.gmm_pi.data = N / N.sum()

            # Обновляем центры
            # weighted_sum: [n_clusters, z_dim]
            weighted_sum = torch.matmul(gamma.T, z)
            self.gmm_mu.data = weighted_sum / N.unsqueeze(1)

            # Обновляем дисперсии
            # Вычисляем квадрат отклонений для каждого объекта и каждого кластера
            # z: [batch_size, 1, z_dim]
            # self.gmm_mu: [1, n_clusters, z_dim]
            z_expanded = z.unsqueeze(1)  # [batch_size, 1, z_dim]
            mu_expanded = self.gmm_mu.unsqueeze(0)  # [1, n_clusters, z_dim]

            # squared_diff: [batch_size, n_clusters, z_dim]
            squared_diff = (z_expanded - mu_expanded) ** 2

            # Взвешенная сумма квадратов отклонений
            # gamma: [batch_size, n_clusters] -> [batch_size, n_clusters, 1]
            gamma_expanded = gamma.unsqueeze(-1)  # [batch_size, n_clusters, 1]

            # weighted_var: [n_clusters, z_dim]
            weighted_var = (gamma_expanded * squared_diff).sum(dim=0)

            # Обновляем logvar
            self.gmm_logvar.data = torch.log(weighted_var / N.unsqueeze(1) + 1e-6)

    def generate_prototypes(self, dataloader, device, temperature=0.3):
        """
        Генерирует прототипы кластеров, усредняя изображения,
        которые с высокой уверенностью принадлежат к каждому кластеру.
        dataloader: DataLoader, который возвращает (изображения, метки).
        """
        self.eval()
        cluster_sums = {i: None for i in range(self.n_clusters)}
        cluster_counts = {i: 0 for i in range(self.n_clusters)}
        confidence_threshold = 0.8

        print("Генерация прототипов кластеров...")
        with torch.no_grad():
            for images, _ in tqdm(dataloader, desc="Обработка батчей"):
                # 1. Извлекаем эмбеддинги с помощью ResNet
                images = images.to(device)
                embeddings = resnet(images)

                # 2. Пропускаем эмбеддинги через VaDE модель
                _, _, gamma, _, _ = self(embeddings, temperature)

                # 3. Для каждого объекта в батче
                for i in range(images.size(0)):
                    max_conf, cluster_id = torch.max(gamma[i], dim=0)
                    if max_conf.item() > confidence_threshold:
                        if cluster_sums[cluster_id.item()] is None:
                            cluster_sums[cluster_id.item()] = images[i].cpu().clone()
                        else:
                            cluster_sums[cluster_id.item()] += images[i].cpu()
                        cluster_counts[cluster_id.item()] += 1

        prototypes = {}
        for c in range(self.n_clusters):
            if cluster_counts[c] > 0:
                prototypes[c] = cluster_sums[c] / cluster_counts[c]
            else:
                prototypes[c] = None
                print(f"Предупреждение: Не найдено изображений с уверенностью > {confidence_threshold} для кластера {c}.")

        return prototypes


class WorkingTrainer:
    def __init__(self, model, device, eta=0.0):
        self.model = model
        self.device = device
        self.eta = eta

    def compute_loss(self, x, x_recon, z, gamma, mu, logvar):
        B = x.shape[0]
        recon_loss = F.mse_loss(x_recon, x, reduction='sum') / B
        log_q_z = -0.5 * torch.sum(
            logvar + (z - mu) ** 2 / torch.exp(logvar) + np.log(2 * np.pi),
            dim=1
        )
        log_p_z = self.model.compute_gmm_prob(z)
        kl_loss = torch.mean(log_q_z - log_p_z)
        expected_center = torch.matmul(gamma, self.model.gmm_mu)
        center_loss = F.mse_loss(z, expected_center, reduction='mean') * 5.0
        entropy = -torch.sum(gamma * torch.log(gamma + 1e-10), dim=1).mean()
        entropy_loss = -self.eta * entropy
        total_loss = recon_loss + 20.0 * kl_loss + center_loss + entropy_loss
        confidence = gamma.max(dim=1)[0].mean()
        return total_loss, {
            'total': total_loss.item(),
            'recon': recon_loss.item(),
            'kl': kl_loss.item(),
            'center': center_loss.item(),
            'entropy': entropy.item(),
            'entropy_loss': entropy_loss.item(),
            'confidence': confidence.item()
        }

    def train_epoch(self, train_loader, optimizer, epoch, temperature=0.3):
        self.model.train()
        epoch_loss = 0
        epoch_entropy = 0

        # Для обновления GMM
        all_z = []
        all_gamma = []

        pbar = tqdm(train_loader, desc=f'Epoch {epoch+1:3d}')
        for batch_idx, x in enumerate(pbar):
            x = x.to(self.device)
            optimizer.zero_grad()
            x_recon, z, gamma, mu, logvar = self.model(x, temperature)

            # Сохраняем для обновления GMM
            all_z.append(z.detach())
            all_gamma.append(gamma.detach())

            loss, loss_dict = self.compute_loss(x, x_recon, z, gamma, mu, logvar)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), 5.0)
            optimizer.step()

            epoch_loss += loss_dict['total']
            epoch_entropy += loss_dict['entropy']
            if batch_idx % 20 == 0:
                pbar.set_postfix({
                    'loss': f"{loss_dict['total']:.1f}",
                    'H(γ)': f"{loss_dict['entropy']:.2f}",
                    'η': f"{self.eta:.2f}"
                })

        # После обработки всех батчей обновляем GMM
        all_z = torch.cat(all_z, dim=0)
        all_gamma = torch.cat(all_gamma, dim=0)
        self.model.update_gmm(all_z, all_gamma)

        return {
            'loss': epoch_loss / len(train_loader),
            'entropy': epoch_entropy / len(train_loader)
        }

    def evaluate(self, data_loader, true_labels, temperature=0.3):
        self.model.eval()
        all_gamma = []
        with torch.no_grad():
            for x in data_loader:
                x = x.to(self.device)
                _, _, gamma, _, _ = self.model(x, temperature)
                all_gamma.append(gamma.cpu().numpy())
        all_gamma = np.vstack(all_gamma)
        pred_labels = np.argmax(all_gamma, axis=1)
        nmi = normalized_mutual_info_score(true_labels, pred_labels)
        ari = adjusted_rand_score(true_labels, pred_labels)
        entropy = -np.sum(all_gamma * np.log(all_gamma + 1e-10), axis=1).mean()
        confidence = all_gamma.max(axis=1).mean()
        return {
            'nmi': nmi,
            'ari': ari,
            'entropy': entropy,
            'confidence': confidence,
            'gamma': all_gamma,
            'pred_labels': pred_labels
        }


def pretrain_autoencoder(model, train_loader, device, epochs=3):
    model.train()
    optimizer = optim.Adam(model.parameters(), lr=1e-3)
    print("Предобучение автоэнкодера...")
    for epoch in range(epochs):
        total_loss = 0
        for x in tqdm(train_loader, desc=f"Предобучение {epoch+1}/{epochs}"):
            x = x.to(device)
            optimizer.zero_grad()
            mu, logvar, gamma = model.encode(x, temperature=1.0)
            z = model.reparameterize(mu, logvar)
            x_recon = model.decode(z)
            loss = F.mse_loss(x_recon, x)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"Epoch {epoch+1}: средний loss = {total_loss/len(train_loader):.4f}")
    return model


def export_to_onnx(model, device, eta, save_dir='onnx_models'):
    """Экспорт модели в формат ONNX"""
    os.makedirs(save_dir, exist_ok=True)

    model.eval()

    # Создаем пример входных данных (batch_size=1, input_dim=512)
    dummy_input = torch.randn(1, 512).to(device)

    # Путь для сохранения (заменяем точку на подчеркивание для Windows)
    eta_str = f"{eta:.2f}".replace('.', '_')
    onnx_path = os.path.join(save_dir, f"model_eta_{eta_str}.onnx")

    # Экспортируем
    torch.onnx.export(
        model,
        dummy_input,
        onnx_path,
        opset_version=13,
        input_names=['input'],
        output_names=['recon', 'z', 'gamma', 'mu', 'logvar'],
        dynamic_axes={
            'input': {0: 'batch_size'},
            'recon': {0: 'batch_size'},
            'z': {0: 'batch_size'},
            'gamma': {0: 'batch_size'},
            'mu': {0: 'batch_size'},
            'logvar': {0: 'batch_size'}
        },
        verbose=False
    )
    print(f"✓ ONNX модель сохранена: {onnx_path}")
    return onnx_path

def get_cluster_interpretation(val_labels, pred_labels, class_names):
    """Автоматически сопоставляет номера кластеров с названиями дефектов"""
    from collections import Counter
    mapping = {}
    for c in range(12):
        mask = (pred_labels == c)
        if np.sum(mask) > 0:
            most_common_idx = Counter(val_labels[mask]).most_common(1)[0][0]
            mapping[c] = class_names[most_common_idx]
        else:
            mapping[c] = f"Unknown_{c}"
    return mapping

def run_experiment_for_eta(eta, device, train_loader, val_loader, val_labels, num_epochs=30):
    print(f"Эксперимент с η = {eta:.2f}")

    start_time = time.time()

    # Создаем модель
    model = WorkingVaDE_Metal(input_dim=512, z_dim=32, n_clusters=12).to(device)

    # Предобучение
    model = pretrain_autoencoder(model, train_loader, device, epochs=10)

    # Тренер
    trainer = WorkingTrainer(model, device, eta=eta)
    optimizer = optim.Adam(model.parameters(), lr=1e-4)

    history = {
        'train_loss': [],
        'train_entropy': [],
        'val_nmi': [],
        'val_ari': [],
        'val_entropy': []
    }

    for epoch in range(num_epochs):
        train_metrics = trainer.train_epoch(train_loader, optimizer, epoch, temperature=0.3)

        if epoch % 2 == 0 or epoch == num_epochs - 1:
            val_metrics = trainer.evaluate(val_loader, val_labels, temperature=0.3)
            history['train_loss'].append(train_metrics['loss'])
            history['train_entropy'].append(train_metrics['entropy'])
            history['val_nmi'].append(val_metrics['nmi'])
            history['val_ari'].append(val_metrics['ari'])
            history['val_entropy'].append(val_metrics['entropy'])

            if epoch % 5 == 0 or epoch < 3:
                print(f"Epoch {epoch+1:3d}: "
                      f"loss={train_metrics['loss']:.1f}, "
                      f"NMI={val_metrics['nmi']:.3f}, "
                      f"H(γ)={val_metrics['entropy']:.3f}")

    final_metrics = trainer.evaluate(val_loader, val_labels, temperature=0.3)
    elapsed_time = time.time() - start_time

    print(f"\nРезультаты для η={eta:.2f}:")
    print(f"  NMI: {final_metrics['nmi']:.4f}")
    print(f"  ARI: {final_metrics['ari']:.4f}")
    print(f"  H(γ): {final_metrics['entropy']:.4f}")
    print(f"  Время: {elapsed_time:.1f} сек")

    # Сохраняем PyTorch модель
    eta_str = f"{eta:.2f}".replace('.', '_')
    pt_path = f"model_eta_{eta_str}.pth"
    torch.save(model.state_dict(), pt_path)
    print(f"✓ PyTorch модель сохранена: {pt_path}")

    # Экспортируем в ONNX
    onnx_path = export_to_onnx(model, device, eta)

    return {
        'model': model,
        'history': history,
        'final_metrics': final_metrics,
        'elapsed_time': elapsed_time,
        'pt_path': pt_path,
        'onnx_path': onnx_path,
        'pred_labels': final_metrics['pred_labels']
    }

def main():
    print("Эксперимент: влияние энтропийной регуляризации на VaDE")

    # Устройство
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Устройство: {device}")

    print("Запуск экспериментов")

    eta_values = [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.15, 0.2]
    results = {}

    # Создаем папки для результатов
    os.makedirs("metal_defects_results", exist_ok=True)
    os.makedirs("onnx_models", exist_ok=True)
    os.makedirs("pytorch_models", exist_ok=True)

    for eta in eta_values:
        results[eta] = run_experiment_for_eta(
            eta, device, train_loader, val_loader, val_labels, num_epochs=30
        )

        # Перемещаем файлы моделей в соответствующие папки
        pt_path = results[eta]['pt_path']
        onnx_path = results[eta]['onnx_path']

        import shutil
        shutil.move(pt_path, os.path.join("pytorch_models", pt_path))
        shutil.move(onnx_path, os.path.join("onnx_models", os.path.basename(onnx_path)))

        results[eta]['pt_path'] = os.path.join("pytorch_models", pt_path)
        results[eta]['onnx_path'] = os.path.join("onnx_models", os.path.basename(onnx_path))

        print(f"✓ Модели перемещены в папки")

        results_dict = {}
    for eta in eta_values:
        m = results[eta]['final_metrics']

        results_dict[f"{eta:.2f}"] = {
            'nmi': float(m['nmi']),
            'ari': float(m['ari']),
            'entropy': float(m['entropy']),
            'time': float(results[eta]['elapsed_time'])
        }

    with open("metal_defects_results/results.json", "w") as f:
        json.dump(results_dict, f, indent=2)

    # Сохранение истории обучения моделей в отдельный JSON
    history_dict = {}
    for eta in eta_values:

        clean_history = {}
        for key, value_list in results[eta]['history'].items():
            clean_history[key] = [float(x) if hasattr(x, 'item') else x for x in value_list]
        history_dict[f"{eta:.2f}"] = clean_history

    with open("metal_defects_results/history.json", "w") as f:
        json.dump(history_dict, f, indent=2)

    print("Сводка результатов:")
    print(f"{'η':<6} {'NMI':<10} {'ARI':<10} {'H(γ)':<10} {'Время (с)':<10}")
    print("-"*70)

    best_eta = None
    best_nmi = -1

    for eta in eta_values:
        m = results[eta]['final_metrics']
        t = results[eta]['elapsed_time']
        print(f"{eta:<6.2f} {m['nmi']:<10.4f} {m['ari']:<10.4f} {m['entropy']:<10.4f} {t:<10.1f}")

        if m['nmi'] > best_nmi:
            best_nmi = m['nmi']
            best_eta = eta

    # Интерпретация кластеров
    best_result = results[best_eta]
    cluster_map = get_cluster_interpretation(
        val_labels,
        best_result['pred_labels'],
        class_names
    )

    print("Интерпретация кластеров (по большинству истинных меток)")
    for c in sorted(cluster_map.keys()):
        print(f"Кластер {c:2d}  →  {cluster_map[c]}")

    eta_str = f"{best_eta:.2f}".replace('.', '_')
    print(f"\n Лучшая модель: η = {best_eta:.2f} (NMI = {best_nmi:.4f})")
    print(f"   ONNX файл: onnx_models/model_eta_{eta_str}.onnx")

    print("Эксперимент завершен")
    print("\nРезультаты сохранены в:")
    print("  - metal_defects_results/results.json")
    print("  - metal_defects_results/history.json")
    print("  - pytorch_models/ - PyTorch модели")
    print("  - onnx_models/ - ONNX модели для C#")
    with open("metal_defects_results/cluster_map.json", "w") as f:
        json.dump(cluster_map, f, indent=2)

    print("✓ cluster_map сохранён в metal_defects_results/cluster_map.json")

if __name__ == "__main__":
    main()

from PIL import Image
import numpy as np
import torch
import json

# Загружаем cluster_map из файла
with open("metal_defects_results/cluster_map.json", "r") as f:
    cluster_map = json.load(f)

def quick_test_inclusion_with_names(eta=0.04, image_path=None):
    """Тест на inclusion с названиями кластеров"""
    model_path = f"pytorch_models/model_eta_{str(eta).replace('.', '_')}.pth"

    model = WorkingVaDE_Metal(input_dim=512, z_dim=32, n_clusters=12).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    if image_path is None:
        inc_path = "Metal-surfaces-defects/inclusion"
        image_path = os.path.join(inc_path, os.listdir(inc_path)[0])

    img = Image.open(image_path).convert('RGB')
    img = base_transform(img).unsqueeze(0).to(device)
    emb = resnet(img).squeeze(0)

    with torch.no_grad():
        _, _, gamma, _, _ = model(emb.unsqueeze(0), temperature=0.2)
        gamma = gamma.cpu().numpy().flatten()

    top3_idx = np.argsort(gamma)[-3:][::-1]
    print(f"=== ТЕСТ НА ИЗОБРАЖЕНИЕ: inclusion ===")
    for i, idx in enumerate(top3_idx):
        name = cluster_map.get(str(idx), f"Cluster_{idx}")   # str(idx) потому что JSON ключи — строки
        print(f"  #{i+1} → {name}  ({gamma[idx]:.3f})")
    print(f"Энтропия: {-np.sum(gamma * np.log(gamma + 1e-10)):.3f}")

# Запуск
quick_test_inclusion_with_names(eta=0.04)

import json
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams, patches
import os
from sklearn.manifold import TSNE
import umap
from sklearn.decomposition import PCA
import torch
import torch.nn.functional as F

def setup_publication_style():
    rcParams.update({
        'font.family': 'serif',
        'font.serif': ['Times New Roman', 'DejaVu Serif', 'STIX'],
        'font.size': 10,
        'axes.titlesize': 11,
        'axes.labelsize': 10,
        'xtick.labelsize': 9,
        'ytick.labelsize': 9,
        'legend.fontsize': 8,
        'figure.figsize': (8.0, 5.0),
        'figure.dpi': 300,
        'figure.facecolor': 'white',
        'axes.linewidth': 0.8,
        'axes.grid': True,
        'grid.alpha': 0.3,
        'grid.linestyle': '--',
        'grid.linewidth': 0.5,
        'lines.linewidth': 1.5,
        'lines.markersize': 5,
        'savefig.dpi': 300,
        'savefig.bbox': 'tight',
        'savefig.format': 'png',
    })

setup_publication_style()

with open("metal_defects_results/history.json", "r") as f:
    history_dict = json.load(f)

with open("metal_defects_results/results.json", "r") as f:
    results_dict = json.load(f)

# Выбор моделей для визуализации
etas = [0.0, 0.04, 0.07]
model_names = {
    0.00: 'Базовая (η=0.00)',
    0.04: 'Оптимальная (η=0.04)',
    0.07: 'Мягкая (η=0.07)'
}
colors = ['#1f77b4', '#2ca02c', '#d62728']

def plot_training_comparison(history_dict, results_dict, etas, save_dir='training_plots'):
    os.makedirs(save_dir, exist_ok=True)

    # Подготовка данных
    training_data = {}
    final_metrics = {}
    for eta in etas:
        eta_str = f"{eta:.2f}"
        h = history_dict[eta_str]
        training_data[eta] = {
            1: (h['train_loss'][0], h['val_nmi'][0], h['val_entropy'][0]),
            3: (h['train_loss'][1], h['val_nmi'][1], h['val_entropy'][1]),
            11: (h['train_loss'][5], h['val_nmi'][5], h['val_entropy'][5]),
            21: (h['train_loss'][10], h['val_nmi'][10], h['val_entropy'][10]),
        }
        final_metrics[eta] = {
            'nmi': results_dict[eta_str]['nmi'],
            'ari': results_dict[eta_str]['ari'],
            'entropy': results_dict[eta_str]['entropy'],
        }

    fig, axes = plt.subplots(1, 3, figsize=(18, 5.5))
    fig.suptitle('Сравнение обучения моделей с различными η', fontsize=14, y=1.02)
    epochs = [1, 3, 11, 21]
    markers = ['o', 's', '^']

    # График 1: Loss
    ax = axes[0]
    for idx, eta in enumerate(etas):
        losses = [training_data[eta][e][0] for e in epochs]
        ax.plot(epochs, losses, marker=markers[idx], color=colors[idx],
                linewidth=2.5, markersize=8, label=model_names[eta])
    ax.set_xlabel('Эпоха', fontsize=11)
    ax.set_ylabel('Функция потерь L', fontsize=11)
    ax.set_title('Сходимость функции потерь', fontsize=12)
    ax.set_yscale('log')
    ax.legend(loc='upper right', fontsize=9)
    ax.grid(True, alpha=0.3)

    # График 2: NMI
    ax = axes[1]
    for idx, eta in enumerate(etas):
        nmis = [training_data[eta][e][1] for e in epochs]
        ax.plot(epochs, nmis, marker=markers[idx], color=colors[idx],
                linewidth=2.5, markersize=8, label=model_names[eta])
    ax.set_xlabel('Эпоха', fontsize=11)
    ax.set_ylabel('NMI', fontsize=11)
    ax.set_title('Качество кластеризации (NMI)', fontsize=12)
    ax.legend(loc='lower right', fontsize=9)
    ax.grid(True, alpha=0.3)

    # График 3: Энтропия
    ax = axes[2]
    for idx, eta in enumerate(etas):
        entropies = [training_data[eta][e][2] for e in epochs]
        ax.plot(epochs, entropies, marker=markers[idx], color=colors[idx],
                linewidth=2.5, markersize=8, label=model_names[eta])
    ax.set_xlabel('Эпоха', fontsize=11)
    ax.set_ylabel('Энтропия H(γ)', fontsize=11)
    ax.set_title('Динамика энтропии', fontsize=12)
    ax.legend(loc='upper left', fontsize=9)
    ax.grid(True, alpha=0.3)
    ax.axhline(y=np.log(12), color='gray', linestyle=':', linewidth=1, alpha=0.7,
               label=f'max H(γ) = {np.log(12):.3f}')

    plt.tight_layout()
    plt.savefig(f'{save_dir}/training_curves.png', dpi=300, bbox_inches='tight')
    plt.show()
    print(f"✓ Графики обучения сохранены в {save_dir}/training_curves.png")


def plot_tsne_umap_with_legend(val_loader, val_labels, etas, device,
                                model_class, save_dir='latent_visualizations'):
    """
    Визуализация t-SNE и UMAP с ЧЁТКОЙ ЛЕГЕНДОЙ по кластерам.

    Args:
        val_loader: DataLoader с валидационными данными
        val_labels: истинные метки (для цвета по классам)
        etas: список значений η для визуализации
        device: torch.device
        model_class: класс модели для загрузки
        save_dir: папка для сохранения
    """
    os.makedirs(save_dir, exist_ok=True)

    # Названия классов для легенды (из вашего датасета)
    class_names = ['crease', 'crescent_gap', 'inclusion', 'oil_spot',
                   'punching_hole', 'rolled_in_scale', 'rolled_pit',
                   'scratches', 'silk_spot', 'waist_folding',
                   'water_spot', 'welding_line']

    # Цветовая схема для 12 кластеров (цветослепобезопасная)
    cluster_colors = plt.cm.tab10(np.linspace(0, 1, 10)).tolist()
    cluster_colors += plt.cm.tab10(np.linspace(0, 0.5, 2)).tolist()  # ещё 2 цвета

    for eta in etas:
        print(f"\n📊 Визуализация для η = {eta:.2f}")

        # Загрузка модели
        eta_str = f"{eta:.2f}".replace('.', '_')
        model_path = f"pytorch_models/model_eta_{eta_str}.pth"

        if not os.path.exists(model_path):
            print(f"  Файл не найден: {model_path}")
            continue

        model = model_class(input_dim=512, z_dim=32, n_clusters=12).to(device)
        model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
        model.eval()

        # Получение латентных представлений и присваиваний
        all_z = []
        all_gamma = []
        with torch.no_grad():
            for x in val_loader:
                x = x.to(device)
                _, z, gamma, _, _ = model(x, temperature=0.3)
                all_z.append(z.cpu().numpy())
                all_gamma.append(gamma.cpu().numpy())

        all_z = np.vstack(all_z)
        all_gamma = np.vstack(all_gamma)
        pred_clusters = np.argmax(all_gamma, axis=1)

        print("  Вычисление t-SNE...")
        tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
        z_tsne = tsne.fit_transform(all_z)

        fig, ax = plt.subplots(1, 1, figsize=(8, 7))

        # Scatter с цветом по предсказанным кластерам
        scatter = ax.scatter(z_tsne[:, 0], z_tsne[:, 1],
                            c=pred_clusters, cmap=plt.cm.tab10,
                            s=15, alpha=0.6, edgecolors='white', linewidth=0.3)

        legend_elements = [patches.Patch(color=cluster_colors[i], label=f'Кластер {i}')
                          for i in range(12)]
        ax.legend(handles=legend_elements, loc='best', fontsize=7, ncol=3, framealpha=0.9)

        ax.set_title(f't-SNE: η = {eta:.2f}\nNMI = {results_dict[f"{eta:.2f}"]["nmi"]:.3f}', fontsize=12)
        ax.set_xlabel('t-SNE 1', fontsize=10)
        ax.set_ylabel('t-SNE 2', fontsize=10)
        ax.grid(True, alpha=0.2)

        plt.tight_layout()
        plt.savefig(f'{save_dir}/tsne_eta_{eta_str}.png', dpi=300, bbox_inches='tight')
        plt.show()

        # ========== UMAP ==========
        print("  Вычисление UMAP...")
        reducer = umap.UMAP(n_components=2, random_state=42, n_neighbors=15, min_dist=0.1)
        z_umap = reducer.fit_transform(all_z)

        fig, ax = plt.subplots(1, 1, figsize=(8, 7))
        scatter = ax.scatter(z_umap[:, 0], z_umap[:, 1],
                            c=pred_clusters, cmap=plt.cm.tab10,
                            s=15, alpha=0.6, edgecolors='white', linewidth=0.3)

        ax.legend(handles=legend_elements, loc='best', fontsize=7, ncol=3, framealpha=0.9)
        ax.set_title(f'UMAP: η = {eta:.2f}\nARI = {results_dict[f"{eta:.2f}"]["ari"]:.3f}', fontsize=12)
        ax.set_xlabel('UMAP 1', fontsize=10)
        ax.set_ylabel('UMAP 2', fontsize=10)
        ax.grid(True, alpha=0.2)

        plt.tight_layout()
        plt.savefig(f'{save_dir}/umap_eta_{eta_str}.png', dpi=300, bbox_inches='tight')
        plt.show()

        fig, ax = plt.subplots(1, 1, figsize=(8, 7))
        scatter = ax.scatter(z_umap[:, 0], z_umap[:, 1],
                            c=val_labels, cmap='tab10',
                            s=15, alpha=0.6, edgecolors='white', linewidth=0.3)

        # Легенда по истинным классам
        class_legend = [patches.Patch(color=plt.cm.tab10(i/12), label=class_names[i])
                       for i in range(12)]
        ax.legend(handles=class_legend, loc='best', fontsize=7, ncol=3, framealpha=0.9)

        ax.set_title(f'UMAP: ИСТИННЫЕ метки (η = {eta:.2f})', fontsize=12)
        ax.set_xlabel('UMAP 1', fontsize=10)
        ax.set_ylabel('UMAP 2', fontsize=10)
        ax.grid(True, alpha=0.2)

        plt.tight_layout()
        plt.savefig(f'{save_dir}/umap_true_labels_eta_{eta_str}.png', dpi=300, bbox_inches='tight')
        plt.show()

        print(f"  ✓ Графики сохранены в {save_dir}/")

    print(f"\n Визуализация завершена! Папка: {save_dir}/")


def plot_additional_diagnostics(val_loader, val_labels, etas, device, model_class, save_dir='latent_visualizations'):
    """Дополнительные диагностические графики"""
    os.makedirs(save_dir, exist_ok=True)

    for eta in etas:
        eta_str = f"{eta:.2f}".replace('.', '_')
        model_path = f"pytorch_models/model_eta_{eta_str}.pth"

        if not os.path.exists(model_path):
            continue

        model = model_class(input_dim=512, z_dim=32, n_clusters=12).to(device)
        model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
        model.eval()

        # Сбор данных
        all_gamma = []
        all_recon_errors = []
        with torch.no_grad():
            for x in val_loader:
                x = x.to(device)
                x_recon, z, gamma, _, _ = model(x)
                all_gamma.append(gamma.cpu().numpy())
                all_recon_errors.append(
                    F.mse_loss(x_recon, x, reduction='none').mean(dim=1).cpu().numpy()
                )

        all_gamma = np.vstack(all_gamma)
        all_recon_errors = np.concatenate(all_recon_errors)
        pred_labels = np.argmax(all_gamma, axis=1)
        confidences = all_gamma.max(axis=1)
        entropies = -np.sum(all_gamma * np.log(all_gamma + 1e-10), axis=1)

        fig, ax = plt.subplots(1, 1, figsize=(6, 4.5))
        ax.hist(entropies, bins=50, edgecolor='black', alpha=0.7, color='steelblue', density=True)
        ax.axvline(x=entropies.mean(), color='red', linestyle='--', linewidth=2,
                   label=f'Средняя: {entropies.mean():.3f}')
        ax.axvline(x=np.log(12), color='gray', linestyle=':', linewidth=1,
                   label=f'max = ln(12) = {np.log(12):.3f}')
        ax.set_xlabel('Энтропия H(γ)', fontsize=10)
        ax.set_ylabel('Плотность', fontsize=10)
        ax.set_title(f'Распределение энтропии (η = {eta:.2f})', fontsize=11)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(f'{save_dir}/entropy_dist_eta_{eta_str}.png', dpi=300, bbox_inches='tight')
        plt.show()

        correct = (pred_labels == val_labels)
        fig, ax = plt.subplots(1, 1, figsize=(6, 4.5))

        # Биннинг по уверенности
        n_bins = 10
        bin_edges = np.linspace(0, 1, n_bins + 1)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

        accuracies = []
        counts = []
        for i in range(n_bins):
            mask = (confidences >= bin_edges[i]) & (confidences < bin_edges[i+1])
            if mask.sum() > 0:
                accuracies.append(correct[mask].mean())
                counts.append(mask.sum())
            else:
                accuracies.append(np.nan)
                counts.append(0)

        ax.errorbar(bin_centers, accuracies, xerr=0.05, fmt='o-', color='steelblue',
                    capsize=3, label='Точность в бине')
        ax.plot([0, 1], [0, 1], 'k--', alpha=0.5, label='Идеальная калибровка')
        ax.set_xlabel('Уверенность модели', fontsize=10)
        ax.set_ylabel('Точность', fontsize=10)
        ax.set_title(f'Калибровка уверенности (η = {eta:.2f})', fontsize=11)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        plt.tight_layout()
        plt.savefig(f'{save_dir}/calibration_eta_{eta_str}.png', dpi=300, bbox_inches='tight')
        plt.show()

        fig, ax = plt.subplots(1, 1, figsize=(6, 4.5))
        cluster_recon = [all_recon_errors[pred_labels == c].mean() for c in range(12)]
        cluster_std = [all_recon_errors[pred_labels == c].std() for c in range(12)]

        ax.bar(range(12), cluster_recon, yerr=cluster_std, capsize=3,
               color=plt.cm.tab10(np.linspace(0, 1, 12)), edgecolor='black')
        ax.set_xlabel('Кластер', fontsize=10)
        ax.set_ylabel('Средняя ошибка реконструкции', fontsize=10)
        ax.set_title(f'Реконструкция по кластерам (η = {eta:.2f})', fontsize=11)
        ax.grid(True, alpha=0.3, axis='y')
        plt.tight_layout()
        plt.savefig(f'{save_dir}/recon_by_cluster_eta_{eta_str}.png', dpi=300, bbox_inches='tight')
        plt.show()

        print(f"  ✓ Доп. графики для η={eta:.2f} сохранены")

    print(f"\nДоп. диагностика завершена! Папка: {save_dir}/")


print("запуск визуализации")

# 1. Графики обучения
plot_training_comparison(history_dict, results_dict, etas)

# 2. t-SNE / UMAP с легендой
plot_tsne_umap_with_legend(
    val_loader=val_loader,
    val_labels=val_labels,
    etas=etas,
    device=device,
    model_class=WorkingVaDE_Metal,
    save_dir='latent_visualizations'
)

# 3. Дополнительные диагностические графики
plot_additional_diagnostics(
    val_loader=val_loader,
    val_labels=val_labels,
    etas=etas,
    device=device,
    model_class=WorkingVaDE_Metal,
    save_dir='latent_visualizations'
)

print("Визуализация подготовлена")
print(f"Результаты в папке: latent_visualizations/")
print("  - training_curves.png")
print("  - tsne_eta_*.png, umap_eta_*.png (с легендой!)")
print("  - entropy_dist_eta_*.png")
print("  - calibration_eta_*.png")
print("  - recon_by_cluster_eta_*.png")

!zip -r results.zip latent_visualizations training_plots metal_defects_results
from google.colab import files
files.download('results.zip')

!zip -r models.zip pytorch_models onnx_models
from google.colab import files
files.download('models.zip')